services:
  chimera:
    image: chimera
    container_name: chimera
    restart: unless-stopped
    volumes:
      - ./.env:/usr/src/chimera/.env
    environment:
      RUST_LOG: "info"
      LAVALINK_PASSWORD: "youshallnotpass"
    depends_on:
      lavalink:
        condition: service_healthy
        restart: true
    networks:
    - lavalink
  
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      _JAVA_OPTIONS: "-Xmx6G"
      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    ports:
      - "2333:2333"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-H",
          "Authorization: youshallnotpass",
          "http://127.0.0.1:2333/version",
        ]
      interval: 1s
      start_period: 10s
      timeout: 1s
      retries: 5



networks:
  lavalink:
    name: lavalink